name: Docker build & publish

on:
  pull_request:
  push:
    branches: [ master ]

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          if [[ "${GITHUB_REF##refs/heads/}" == "master" ]]; then
            echo "tags=phpdockerio/readability-js-server:latest" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME=${GITHUB_REF##refs/heads/}
            echo "tags=phpdockerio/readability-js-server:${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build & push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          pull: true
          tags: ${{ steps.docker_tags.outputs.tags }}
